In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
df1=pd.read_csv('football_dataset/epl_final.csv')
df1.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,14,4,6,6,13,12,1,2,0,0
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,10,5,7,7,19,14,1,2,0,0
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,3,9,8,4,15,21,5,3,1,0
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,4,6,5,8,11,13,1,1,0,0
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,8,6,6,4,21,20,1,3,0,0

In [3]:
df1.columns

Index(['Season', 'MatchDate', 'HomeTeam', 'AwayTeam', 'FullTimeHomeGoals',
       'FullTimeAwayGoals', 'FullTimeResult', 'HalfTimeHomeGoals',
       'HalfTimeAwayGoals', 'HalfTimeResult', 'HomeShots', 'AwayShots',
       'HomeShotsOnTarget', 'AwayShotsOnTarget', 'HomeCorners', 'AwayCorners',
       'HomeFouls', 'AwayFouls', 'HomeYellowCards', 'AwayYellowCards',
       'HomeRedCards', 'AwayRedCards'],
      dtype='object')

In [4]:
df1.shape

(9380, 22)

In [5]:
df1.describe()

,FullTimeHomeGoals,FullTimeAwayGoals,HalfTimeHomeGoals,HalfTimeAwayGoals,HomeShots,AwayShots,HomeShotsOnTarget,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards
count,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000,9380.000000
mean,1.535394,1.182623,0.688273,0.518763,13.617484,10.810661,5.973134,4.693710,6.040299,4.774733,11.276333,11.765672,1.468124,1.792431,0.062473,0.085288
std,1.305432,1.157414,0.835079,0.735357,5.356424,4.696501,3.267954,2.750045,3.110619,2.749541,3.750250,3.924179,1.217190,1.288481,0.253221,0.290183
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,10.000000,7.000000,4.000000,3.000000,4.000000,3.000000,9.000000,9.000000,1.000000,1.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,13.000000,10.000000,6.000000,4.000000,6.000000,4.000000,11.000000,12.000000,1.000000,2.000000,0.000000,0.000000
75%,2.000000,2.000000,1.000000,1.000000,17.000000,14.000000,8.000000,6.000000,8.000000,6.000000,14.000000,14.000000,2.000000,3.000000,0.000000,0.000000
max,9.000000,9.000000,5.000000,5.000000,43.000000,37.000000,24.000000,20.000000,20.000000,19.000000,33.000000,29.000000,7.000000,9.000000,3.000000,2.000000

In [6]:
home_df = pd.DataFrame({
    "MatchDate": df1["MatchDate"],
    "Season": df1["Season"],

    "Team": df1["HomeTeam"],
    "Opponent": df1["AwayTeam"],

    "Venue": "Home",
    "Shots":df1['HomeShotsOnTarget'],
    "GoalsFor": df1["FullTimeHomeGoals"],
    "GoalsAgainst": df1["FullTimeAwayGoals"],

    "Result": df1["FullTimeResult"],
    "RedCard": df1['HomeRedCards']
})
away_df=pd.DataFrame({
    "MatchDate": df1["MatchDate"],
    "Season": df1["Season"],

    "Team": df1["AwayTeam"],
    "Opponent": df1["HomeTeam"],

    "Venue": "Away",
    "Shots":df1['AwayShotsOnTarget'],
    "GoalsFor": df1["FullTimeAwayGoals"],
    "GoalsAgainst": df1["FullTimeHomeGoals"],
    "Result": df1["FullTimeResult"],
    "RedCard": df1['AwayRedCards']
})

In [7]:
away_df.sample(10)

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard
5081,2014-02-01,2013/14,Aston Villa,Everton,Away,1,1,2,H,0
4046,2011-04-25,2010/11,Man City,Blackburn,Away,5,1,0,A,0
8039,2021-12-10,2021/22,Watford,Brentford,Away,2,1,2,H,0
558,2001-12-26,2001/02,Chelsea,Arsenal,Away,3,1,2,H,0
8531,2023-03-15,2022/23,Crystal Palace,Brighton,Away,3,0,1,H,0
7973,2021-10-23,2021/22,Watford,Everton,Away,8,5,2,A,0
8247,2022-05-12,2021/22,Arsenal,Tottenham,Away,4,0,3,H,1
6712,2018-04-22,2017/18,Burnley,Stoke,Away,7,1,1,D,0
2041,2006-02-01,2005/06,Birmingham,Liverpool,Away,2,1,1,D,1
8589,2023-04-26,2022/23,Liverpool,West Ham,Away,4,2,1,A,0

In [8]:
team_df = pd.concat(
    [home_df, away_df],
    ignore_index=True
)

In [9]:
team_df = (
    team_df
    .sort_values(["Team", "MatchDate"])
    .reset_index(drop=True)
)
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0

In [10]:
team_df["GoalsConcededL5"] = (
    team_df.groupby("Team")["GoalsAgainst"]
           .transform(
               lambda s: s.shift(1).rolling(5, min_periods=1).mean()
           )
)

In [11]:
team_df["GoalsMeanL5"] = (
    team_df.groupby("Team")["GoalsFor"]
           .transform(
               lambda s: s.shift(1).rolling(5, min_periods=1).mean()
           )
)

In [12]:
team_df["ShotsOTMeanL5"] = (
    team_df.groupby("Team")["Shots"]
           .transform(
               lambda s: s.shift(1).rolling(5, min_periods=1).mean()
           )
)

In [13]:
team_df.sample(10)

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,GoalsConcededL5,GoalsMeanL5,ShotsOTMeanL5
13838,2003-12-21,2003/04,Southampton,Portsmouth,Home,7,3,0,H,0,1.0,1.0,5.8
1016,2002-09-01,2002/03,Aston Villa,Bolton,Away,5,0,1,H,0,0.8,1.2,7.0
16332,2022-02-23,2021/22,Tottenham,Burnley,Away,2,0,1,H,0,2.2,1.6,5.6
16635,2019-02-09,2018/19,Watford,Everton,Home,2,1,0,H,0,1.2,1.2,2.0
15286,2012-04-11,2011/12,Swansea,QPR,Away,6,0,3,H,0,1.4,1.0,7.0
17016,2014-04-05,2013/14,West Brom,Norwich,Away,5,1,0,A,0,2.0,1.2,4.4
14003,2015-08-09,2015/16,Southampton,Newcastle,Away,5,2,2,D,0,1.8,1.8,4.8
2224,2007-01-31,2006/07,Blackburn,Chelsea,Away,4,0,3,H,0,1.0,1.8,5.4
4216,2004-01-07,2003/04,Charlton,Man City,Away,4,1,1,D,0,1.0,1.4,7.8
3815,2018-05-06,2017/18,Burnley,Arsenal,Away,2,0,5,H,0,1.0,1.2,4.0

In [14]:
def get_points(df):
    if (df['Venue']=='Home' and df['Result']=='H') or (df['Venue']=='Away' and df['Result']=='A'):
        point=3
    elif df['Result']=='D':
        point=1
    else:
        point=0
    return point

In [15]:
team_df['points']=team_df.apply(get_points,axis=1)
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,GoalsConcededL5,GoalsMeanL5,ShotsOTMeanL5,points
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1,NaN,NaN,NaN,0
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1,1.000000,0.000000,7.000000,3
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0,0.500000,1.000000,9.500000,3
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0,1.333333,2.333333,9.333333,1
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0,1.500000,2.250000,8.250000,1

In [21]:
team_df["PointsMeanL5"] = (
    team_df.groupby("Team")["points"]
           .transform(
               lambda s: s.shift(1).rolling(5, min_periods=1).mean()
           )
)
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,GoalsMeanL5,ShotsOTMeanL5,points,PointsMeanL5,goal_df,GoalDFMeanL5,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1,...,NaN,NaN,0,NaN,-1,NaN,NaN,NaN,NaN,NaN
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1,...,0.000000,7.000000,3,0.00,2,-1.00,1.0,-1.00,7.000000,0.00
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0,...,1.000000,9.500000,3,1.50,2,0.50,1.0,0.50,9.500000,1.50
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0,...,2.333333,9.333333,1,2.00,0,1.00,0.5,1.00,9.333333,2.00
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0,...,2.250000,8.250000,1,1.75,0,0.75,0.0,0.75,8.250000,1.75

In [22]:
def create_rolling_feature(df,source,column,window):
    feature=df.groupby(source)[column].transform(
        lambda s:s.shift(1).rolling(window,min_periods=1).mean()
    )
    return feature

In [23]:
team_df['goal_df']=team_df.GoalsFor - team_df.GoalsAgainst
team_df['GoalDFMeanL5']=create_rolling_feature(team_df,'Team','goal_df',5)
team_df['RedCardL2']= create_rolling_feature(team_df,'Team','RedCard',2)
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,GoalsMeanL5,ShotsOTMeanL5,points,PointsMeanL5,goal_df,GoalDFMeanL5,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1,...,NaN,NaN,0,NaN,-1,NaN,NaN,NaN,NaN,NaN
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1,...,0.000000,7.000000,3,0.00,2,-1.00,1.0,-1.00,7.000000,0.00
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0,...,1.000000,9.500000,3,1.50,2,0.50,1.0,0.50,9.500000,1.50
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0,...,2.333333,9.333333,1,2.00,0,1.00,0.5,1.00,9.333333,2.00
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0,...,2.250000,8.250000,1,1.75,0,0.75,0.0,0.75,8.250000,1.75

In [24]:
team_df['GoalDFMeanL10']=create_rolling_feature(team_df,'Team','goal_df',10)
team_df['ShotsOTMeanL10']=create_rolling_feature(team_df,'Team','Shots',10)
team_df['PointsMeanL10']=create_rolling_feature(team_df,'Team','points',10)
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,GoalsMeanL5,ShotsOTMeanL5,points,PointsMeanL5,goal_df,GoalDFMeanL5,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1,...,NaN,NaN,0,NaN,-1,NaN,NaN,NaN,NaN,NaN
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1,...,0.000000,7.000000,3,0.00,2,-1.00,1.0,-1.00,7.000000,0.00
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0,...,1.000000,9.500000,3,1.50,2,0.50,1.0,0.50,9.500000,1.50
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0,...,2.333333,9.333333,1,2.00,0,1.00,0.5,1.00,9.333333,2.00
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0,...,2.250000,8.250000,1,1.75,0,0.75,0.0,0.75,8.250000,1.75

In [25]:
team_df.sample(10)

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,GoalsMeanL5,ShotsOTMeanL5,points,PointsMeanL5,goal_df,GoalDFMeanL5,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10
128,2003-12-06,2003/04,Arsenal,Leicester,Away,5,1,1,D,1,...,2.0,7.6,1,2.2,0,1.4,0.0,1.0,7.0,2.2
2846,2011-10-22,2011/12,Bolton,Sunderland,Home,8,0,2,A,0,...,1.0,8.8,0,0.6,-2,-2.2,0.0,-1.3,7.6,0.6
14955,2009-09-19,2009/10,Sunderland,Burnley,Away,5,1,3,H,0,...,1.6,6.2,0,1.8,-2,0.4,0.0,-0.6,5.9,1.0
5397,2014-11-03,2014/15,Crystal Palace,Sunderland,Home,1,1,3,A,1,...,1.6,4.2,0,1.4,-2,0.0,0.5,-0.3,4.3,1.0
4109,2001-02-11,2000/01,Charlton,Newcastle,Home,4,2,0,H,0,...,0.8,4.4,3,1.8,2,0.4,0.0,-0.1,6.1,1.6
8163,2023-05-28,2022/23,Leeds,Tottenham,Home,2,1,4,A,0,...,1.2,3.6,0,0.4,-3,-1.2,0.5,-1.8,4.1,0.5
2982,2018-03-17,2017/18,Bournemouth,West Brom,Home,5,2,1,H,0,...,1.4,4.2,3,1.0,1,-1.0,0.0,0.0,4.9,1.6
6344,2012-01-04,2011/12,Everton,Bolton,Home,4,1,2,A,0,...,0.8,6.6,0,1.6,-1,0.2,0.0,0.1,7.7,1.4
810,2022-02-19,2021/22,Arsenal,Brentford,Home,8,2,1,H,0,...,2.2,5.4,3,2.0,1,1.6,0.5,1.3,5.7,1.9
7684,2013-10-05,2013/14,Hull,Aston Villa,Home,1,0,0,D,0,...,1.2,3.0,1,2.0,0,0.2,0.0,-0.4,4.4,1.2

In [26]:
team_df['GoalsMeanL10']=create_rolling_feature(team_df,'Team','GoalsFor',10)
team_df['GoalsConcededL10']=create_rolling_feature(team_df,'Team','GoalsAgainst',10)

In [27]:
result_map={
    0:'L',
    1:'D',
    3:'W'
}
team_df['outcome']=team_df['points'].map(result_map)
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,PointsMeanL5,goal_df,GoalDFMeanL5,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,outcome
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1,...,NaN,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1,...,0.00,2,-1.00,1.0,-1.00,7.000000,0.00,0.000000,1.000000,W
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0,...,1.50,2,0.50,1.0,0.50,9.500000,1.50,1.000000,0.500000,W
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0,...,2.00,0,1.00,0.5,1.00,9.333333,2.00,2.333333,1.333333,D
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0,...,1.75,0,0.75,0.0,0.75,8.250000,1.75,2.250000,1.500000,D

In [28]:
def calc_win_streak(results):
    streak=0
    out=[]
    for result in results:
        out.append(streak)
        if result=='W':
            streak+=1
        elif result=='L' or result=='D':
            streak=0
    return out

In [29]:
team_df['win_streak']=team_df.groupby('Team')['outcome'].transform(calc_win_streak)
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,goal_df,GoalDFMeanL5,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,outcome,win_streak
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1,...,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L,0
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1,...,2,-1.00,1.0,-1.00,7.000000,0.00,0.000000,1.000000,W,0
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0,...,2,0.50,1.0,0.50,9.500000,1.50,1.000000,0.500000,W,1
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0,...,0,1.00,0.5,1.00,9.333333,2.00,2.333333,1.333333,D,2
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0,...,0,0.75,0.0,0.75,8.250000,1.75,2.250000,1.500000,D,0

In [30]:
team_df.sample(10)

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,goal_df,GoalDFMeanL5,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,outcome,win_streak
556,2015-05-11,2014/15,Arsenal,Swansea,Home,9,0,1,A,0,...,-1,1.4,0.0,1.5,6.1,2.8,2.1,0.6,L,1
16561,2017-03-18,2016/17,Watford,Crystal Palace,Away,2,0,1,H,0,...,-1,-0.2,0.0,-0.6,3.6,1.0,1.2,1.8,L,0
13318,2010-03-15,2009/10,Portsmouth,Liverpool,Away,3,1,4,H,0,...,-3,-1.2,0.5,-1.4,6.9,0.5,0.7,2.1,L,0
13816,2003-04-19,2002/03,Southampton,Leeds,Home,7,3,2,H,0,...,1,0.0,0.0,-0.3,6.1,1.0,1.0,1.3,W,0
3902,2020-12-05,2020/21,Burnley,Everton,Home,3,1,1,D,0,...,0,-1.6,0.0,-1.4,2.6,0.5,0.5,1.9,D,0
9346,2019-01-12,2018/19,Liverpool,Brighton,Away,3,1,0,A,0,...,1,2.2,0.0,2.3,7.3,2.7,2.8,0.5,W,0
3842,2019-02-09,2018/19,Burnley,Brighton,Away,5,3,1,A,0,...,2,0.4,0.0,-0.2,3.6,1.5,1.2,1.4,W,0
910,2024-10-27,2024/25,Arsenal,Liverpool,Home,3,2,2,D,0,...,0,0.6,0.5,0.9,5.7,2.3,1.8,0.9,D,0
16174,2017-12-16,2017/18,Tottenham,Man City,Away,2,1,4,H,0,...,-3,1.0,0.0,0.7,5.4,1.7,1.6,0.9,L,2
12019,2005-08-28,2005/06,Newcastle,Man United,Home,4,0,2,A,0,...,-2,-1.2,0.0,-0.7,6.5,0.9,0.6,1.3,L,0

In [31]:
team_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18760 entries, 0 to 18759
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MatchDate         18760 non-null  object
 1   Season            18760 non-null  object
 2   Team              18760 non-null  object
 3   Opponent          18760 non-null  object
 4   Venue             18760 non-null  object
 5   Shots             18760 non-null  int64
 6   GoalsFor          18760 non-null  int64
 7   GoalsAgainst      18760 non-null  int64
 8   Result            18760 non-null  object
 9   RedCard           18760 non-null  int64
 10  GoalsConcededL5   18714 non-null  float64
 11  GoalsMeanL5       18714 non-null  float64
 12  ShotsOTMeanL5     18714 non-null  float64
 13  points            18760 non-null  int64
 14  PointsMeanL5      18714 non-null  float64
 15  goal_df           18760 non-null  int64
 16  GoalDFMeanL5      18714 non-null  float64
 17  RedCardL2         18714 non-null  float64
 18  GoalDFMeanL10     18714 non-null  float64
 19  ShotsOTMeanL10    18714 non-null  float64
 20  PointsMeanL10     18714 non-null  float64
 21  GoalsMeanL10      18714 non-null  float64
 22  GoalsConcededL10  18714 non-null  float64
 23  outcome           18760 non-null  object
 24  win_streak        18760 non-null  int64
dtypes: float64(11), int64(7), object(7)
memory usage: 3.6+ MB

In [32]:
team_df['MatchDate']=pd.to_datetime(team_df['MatchDate'])

In [33]:
team_df = (
    team_df
    .sort_values(['Team', 'MatchDate'])
    .reset_index(drop=True)
)
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,goal_df,GoalDFMeanL5,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,outcome,win_streak
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1,...,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L,0
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1,...,2,-1.00,1.0,-1.00,7.000000,0.00,0.000000,1.000000,W,0
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0,...,2,0.50,1.0,0.50,9.500000,1.50,1.000000,0.500000,W,1
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0,...,0,1.00,0.5,1.00,9.333333,2.00,2.333333,1.333333,D,2
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0,...,0,0.75,0.0,0.75,8.250000,1.75,2.250000,1.500000,D,0

In [34]:
team_df['RestDays']=(team_df.groupby('Team')['MatchDate'].diff().dt.days)
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,GoalDFMeanL5,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,outcome,win_streak,RestDays
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L,0,NaN
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1,...,-1.00,1.0,-1.00,7.000000,0.00,0.000000,1.000000,W,0,2.0
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0,...,0.50,1.0,0.50,9.500000,1.50,1.000000,0.500000,W,1,5.0
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0,...,1.00,0.5,1.00,9.333333,2.00,2.333333,1.333333,D,2,11.0
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0,...,0.75,0.0,0.75,8.250000,1.75,2.250000,1.500000,D,0,3.0

In [35]:
team_df['H2H']=team_df.groupby(['Team','Opponent'])['points'].transform(
        lambda s:s.shift(1).rolling(5,min_periods=1).mean()
    )
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,outcome,win_streak,RestDays,H2H
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,L,0,NaN,NaN
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1,...,1.0,-1.00,7.000000,0.00,0.000000,1.000000,W,0,2.0,NaN
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0,...,1.0,0.50,9.500000,1.50,1.000000,0.500000,W,1,5.0,NaN
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0,...,0.5,1.00,9.333333,2.00,2.333333,1.333333,D,2,11.0,NaN
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0,...,0.0,0.75,8.250000,1.75,2.250000,1.500000,D,0,3.0,NaN

In [36]:
team_df.drop(columns=['H2H'],inplace=True)

In [37]:
team_df['H2HL5']=create_rolling_feature(team_df,['Team','Opponent'],'points',5)
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,outcome,win_streak,RestDays,H2HL5
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,L,0,NaN,NaN
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1,...,1.0,-1.00,7.000000,0.00,0.000000,1.000000,W,0,2.0,NaN
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0,...,1.0,0.50,9.500000,1.50,1.000000,0.500000,W,1,5.0,NaN
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0,...,0.5,1.00,9.333333,2.00,2.333333,1.333333,D,2,11.0,NaN
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0,...,0.0,0.75,8.250000,1.75,2.250000,1.500000,D,0,3.0,NaN

In [38]:
team_df.sample(10)

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,outcome,win_streak,RestDays,H2HL5
12245,2012-08-25,2012/13,Newcastle,Chelsea,Away,5,0,2,H,0,...,0.0,0.6,6.0,2.1,1.7,1.1,L,1,7.0,1.0
36,2001-05-15,2000/01,Arsenal,Newcastle,Away,1,0,0,D,0,...,0.0,0.7,7.9,2.2,1.9,1.2,D,3,10.0,3.0
10381,2021-09-18,2021/22,Man City,Southampton,Home,1,0,0,D,0,...,0.0,1.7,5.7,2.1,2.7,1.0,D,3,7.0,2.4
11173,2017-11-05,2017/18,Man United,Chelsea,Away,2,0,1,H,0,...,0.0,1.9,5.4,2.3,2.3,0.4,L,1,8.0,1.0
12499,2020-02-29,2019/20,Newcastle,Burnley,Home,4,0,0,D,0,...,0.5,-1.0,2.6,0.9,0.7,1.7,D,0,7.0,1.4
14012,2015-10-25,2015/16,Southampton,Liverpool,Away,3,1,1,D,1,...,0.0,0.1,5.6,1.3,1.5,1.4,D,0,8.0,1.2
15941,2011-12-03,2011/12,Tottenham,Bolton,Home,16,3,0,H,0,...,0.0,1.7,10.1,2.8,2.5,0.8,W,5,7.0,1.4
12169,2010-08-22,2010/11,Newcastle,Aston Villa,Home,14,6,0,H,0,...,0.5,-1.1,4.9,0.5,0.5,1.6,W,0,6.0,1.4
16723,2022-05-22,2021/22,Watford,Chelsea,Away,3,1,2,H,0,...,0.0,-1.9,2.1,0.4,0.6,2.5,L,0,7.0,0.0
12170,2010-08-28,2010/11,Newcastle,Wolves,Away,6,1,1,D,0,...,0.0,-0.3,5.5,0.8,1.0,1.3,D,1,6.0,1.0

In [39]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Season             9380 non-null   object
 1   MatchDate          9380 non-null   object
 2   HomeTeam           9380 non-null   object
 3   AwayTeam           9380 non-null   object
 4   FullTimeHomeGoals  9380 non-null   int64
 5   FullTimeAwayGoals  9380 non-null   int64
 6   FullTimeResult     9380 non-null   object
 7   HalfTimeHomeGoals  9380 non-null   int64
 8   HalfTimeAwayGoals  9380 non-null   int64
 9   HalfTimeResult     9380 non-null   object
 10  HomeShots          9380 non-null   int64
 11  AwayShots          9380 non-null   int64
 12  HomeShotsOnTarget  9380 non-null   int64
 13  AwayShotsOnTarget  9380 non-null   int64
 14  HomeCorners        9380 non-null   int64
 15  AwayCorners        9380 non-null   int64
 16  HomeFouls          9380 non-null   int64
 17  AwayFouls          9380 non-null   int64
 18  HomeYellowCards    9380 non-null   int64
 19  AwayYellowCards    9380 non-null   int64
 20  HomeRedCards       9380 non-null   int64
 21  AwayRedCards       9380 non-null   int64
dtypes: int64(16), object(6)
memory usage: 1.6+ MB

In [40]:
df1['era']=df1['Season'].apply(lambda x:2026-int(x.split('/')[0]))
df1.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,AwayShotsOnTarget,HomeCorners,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards,era
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,4,6,6,13,12,1,2,0,0,26
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,5,7,7,19,14,1,2,0,0,26
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,9,8,4,15,21,5,3,1,0,26
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,6,5,8,11,13,1,1,0,0,26
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,6,6,4,21,20,1,3,0,0,26

In [41]:
def rolling_HW_goals_scored(df,window=5):
    df = df.sort_values("MatchDate").copy()
    df["HomeGoalsMeanL5"] = (
        df.groupby("HomeTeam")["FullTimeHomeGoals"]
          .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )

    df["AwayGoalsMeanL5"] = (
        df.groupby("AwayTeam")["FullTimeAwayGoals"]
          .transform(lambda x: x.shift(1).rolling(window, min_periods=1).mean())
    )

    return df

In [42]:
def rolling_HW_goals_conceded(df,window=5):
    df=df.sort_values('MatchDate').copy()
    df['HomeGoalsConcededL5']=(df.groupby('HomeTeam')['FullTimeAwayGoals']
        .transform(lambda x:x.shift(1).rolling(window,min_periods=1).mean())
                            )
    df['AwayGoalsConcededL5']=(df.groupby('AwayTeam')['FullTimeHomeGoals']
        .transform(lambda x:x.shift(1).rolling(window,min_periods=1).mean())
                            )
    return df

In [43]:
df2=rolling_HW_goals_scored(df1,5)
df2.sample(10)

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,AwayCorners,HomeFouls,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards,era,HomeGoalsMeanL5,AwayGoalsMeanL5
740,2001/02,2002-04-27,Derby,Leeds,0,1,A,0,1,A,...,6,12,19,2,0,0,0,25,1.4,1.2
5777,2015/16,2015-12-20,Swansea,West Ham,0,0,D,0,0,D,...,9,6,9,0,1,0,0,11,0.8,1.2
8441,2022/23,2023-01-04,Southampton,Nott'm Forest,0,1,A,0,1,A,...,2,14,17,2,2,0,0,4,1.0,0.0
5133,2013/14,2014-03-15,Fulham,Newcastle,1,0,H,0,0,D,...,7,11,6,1,0,0,0,13,1.2,1.4
1533,2004/05,2004-09-20,Man United,Liverpool,2,1,H,1,0,H,...,2,22,15,1,2,0,0,22,1.0,1.0
1595,2004/05,2004-11-13,Bolton,Aston Villa,1,2,A,1,1,D,...,5,10,17,1,1,0,0,22,1.4,0.8
8161,2021/22,2022-03-12,Brighton,Liverpool,0,2,A,0,1,A,...,6,12,15,3,1,0,0,5,0.8,1.6
4880,2013/14,2013-09-14,Aston Villa,Newcastle,1,2,A,0,1,A,...,2,9,11,1,4,0,0,13,1.8,0.6
8984,2023/24,2024-04-24,Man United,Sheffield United,4,2,H,1,1,D,...,4,7,9,0,1,0,0,3,2.0,1.2
8332,2022/23,2022-09-17,Wolves,Man City,0,3,A,0,2,A,...,7,7,9,2,1,1,0,4,0.8,2.6

In [44]:
df2=rolling_HW_goals_conceded(df2,5)
df2.sample(10)

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,AwayFouls,HomeYellowCards,AwayYellowCards,HomeRedCards,AwayRedCards,era,HomeGoalsMeanL5,AwayGoalsMeanL5,HomeGoalsConcededL5,AwayGoalsConcededL5
6421,2017/18,2017-09-23,Everton,Bournemouth,2,1,H,0,0,D,...,11,3,1,0,0,9,1.0,0.4,1.4,1.8
6174,2016/17,2016-12-31,Liverpool,Man City,1,0,H,1,0,H,...,12,2,1,0,0,10,3.2,2.6,1.0,1.2
8394,2022/23,2022-10-30,Arsenal,Nott'm Forest,5,0,H,1,0,H,...,8,0,1,0,0,4,2.8,0.2,1.4,2.4
3524,2009/10,2009-12-30,Man United,Wigan,5,0,H,3,0,H,...,11,0,1,0,0,17,2.0,1.4,0.4,3.6
6919,2018/19,2018-12-16,Southampton,Arsenal,3,2,H,2,1,H,...,10,3,1,0,0,8,1.0,2.6,1.6,1.4
4263,2011/12,2011-12-26,Stoke,Aston Villa,0,0,D,0,0,D,...,10,3,0,0,0,15,2.0,1.0,1.6,1.8
8112,2021/22,2022-02-10,Liverpool,Leicester,2,0,H,1,0,H,...,7,1,0,0,0,5,3.0,1.8,0.2,2.4
7954,2021/22,2021-10-02,Wolves,Newcastle,2,1,H,1,1,D,...,5,0,2,0,0,5,0.6,1.6,1.4,1.8
5938,2015/16,2016-04-16,Norwich,Sunderland,0,3,A,0,1,A,...,11,2,2,0,0,11,1.2,1.0,1.8,1.8
3626,2009/10,2010-03-20,Stoke,Tottenham,1,2,A,0,0,D,...,9,2,2,1,0,17,1.2,0.8,1.0,0.8

In [45]:
def rolling_HW_shots_onTarget(df,window=5):
    df=df.sort_values('MatchDate').copy()
    df['HomeShotTarget']=(df.groupby('HomeTeam')['HomeShotsOnTarget']
        .transform(lambda x:x.shift(1).rolling(window,min_periods=1).mean())
                            )
    df['AwayShotTarget']=(df.groupby('AwayTeam')['AwayShotsOnTarget']
        .transform(lambda x:x.shift(1).rolling(window,min_periods=1).mean())
                            )

In [46]:
df2['ho_goal_df']=df2.FullTimeHomeGoals - df2.FullTimeAwayGoals
df2['HomeGoalDFMeanL5']=create_rolling_feature(df2,'HomeTeam','ho_goal_df',5)
df2['aw_goal_df']=df2.FullTimeAwayGoals - df2.FullTimeHomeGoals
df2['AwayGoalDFMeanL5']=round(create_rolling_feature(df2,'AwayTeam','aw_goal_df',5),2)
df2.sample(10)

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,AwayRedCards,era,HomeGoalsMeanL5,AwayGoalsMeanL5,HomeGoalsConcededL5,AwayGoalsConcededL5,ho_goal_df,HomeGoalDFMeanL5,aw_goal_df,AwayGoalDFMeanL5
110,2000/01,2000-11-04,Coventry,Man United,1,2,A,0,2,A,...,0,26,0.6,1.8,1.8,1.0,-1,-1.2,1,0.8
634,2001/02,2002-02-09,Ipswich,Liverpool,0,6,A,0,2,A,...,0,25,2.0,1.4,0.4,0.8,-6,1.6,6,0.6
8117,2021/22,2022-02-12,Watford,Brighton,0,2,A,0,1,A,...,0,5,0.6,1.4,2.6,1.2,-2,-2.0,2,0.2
6156,2016/17,2016-12-18,Bournemouth,Southampton,1,3,A,1,1,D,...,0,10,2.4,0.4,1.2,1.2,-2,1.2,2,-0.8
2431,2006/07,2007-01-30,Sheffield United,Fulham,2,0,H,2,0,H,...,0,20,1.2,1.4,1.0,2.6,2,0.2,-2,-1.2
550,2001/02,2001-12-22,Derby,Aston Villa,3,1,H,1,1,D,...,0,25,0.8,1.2,0.6,2.2,2,0.2,-2,-1.0
8408,2022/23,2022-11-12,Liverpool,Southampton,3,1,H,3,1,H,...,0,4,1.6,0.2,1.2,1.4,2,0.4,-2,-1.2
5165,2013/14,2014-03-31,Sunderland,West Ham,1,2,A,0,1,A,...,0,13,0.6,1.0,1.0,0.8,-1,-0.4,1,0.2
2327,2006/07,2006-11-26,Tottenham,Wigan,3,1,H,2,1,H,...,0,20,1.0,1.0,0.8,1.0,2,0.2,-2,0.0
8068,2021/22,2021-12-28,Watford,West Ham,1,4,A,1,2,A,...,0,5,1.2,1.0,2.4,1.2,-3,-1.2,3,-0.2

In [47]:
def get_ho_points(df):
    if df['FullTimeResult']=='D':
        ho=1
    elif df['FullTimeResult']=='H':
        ho=3
    else:
        ho=0
    return ho
def get_aw_points(df):
    if df['FullTimeResult']=='D':
        aw=1
    elif df['FullTimeResult']=='H':
        aw=0
    else:
        aw=3
    return aw
df2['ho_win_point']=df2.apply(get_ho_points,axis=1)
df2['aw_win_point']=df2.apply(get_aw_points,axis=1)
df2['HomePointsL5']=create_rolling_feature(df2,'HomeTeam','ho_win_point',5)
df2['AwayPointsL5']=create_rolling_feature(df2,'AwayTeam','aw_win_point',5)
df2.drop(columns=['ho_win_point','aw_win_point','aw_goal_df','ho_goal_df'],inplace=True)
df2.sample(5)

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,AwayRedCards,era,HomeGoalsMeanL5,AwayGoalsMeanL5,HomeGoalsConcededL5,AwayGoalsConcededL5,HomeGoalDFMeanL5,AwayGoalDFMeanL5,HomePointsL5,AwayPointsL5
4002,2010/11,2011-03-19,Stoke,Newcastle,4,0,H,1,0,H,...,0,16,1.6,0.8,1.0,0.4,0.6,0.4,2.0,1.6
4841,2012/13,2013-05-19,Liverpool,QPR,1,0,H,1,0,H,...,0,14,2.0,1.2,0.8,1.8,1.2,-0.6,1.8,0.8
4805,2012/13,2013-04-21,Tottenham,Man City,3,1,H,0,1,A,...,0,14,1.4,0.8,1.2,1.2,0.2,-0.4,1.6,1.4
8715,2023/24,2023-09-30,Wolves,Man City,2,1,H,1,0,H,...,0,3,1.2,1.8,1.6,0.8,-0.4,1.0,1.4,2.0
8652,2023/24,2023-08-12,Bournemouth,West Ham,1,1,D,0,0,D,...,0,3,1.0,1.6,2.2,2.2,-1.2,-0.6,0.6,0.6

In [48]:
df2.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,AwayRedCards,era,HomeGoalsMeanL5,AwayGoalsMeanL5,HomeGoalsConcededL5,AwayGoalsConcededL5,HomeGoalDFMeanL5,AwayGoalDFMeanL5,HomePointsL5,AwayPointsL5
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,0,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,0,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,0,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,0,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,0,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
def get_ho(df):
    if df['FullTimeResult']=='D':
        ho='D'
    elif df['FullTimeResult']=='H':
        ho='W'
    else:
        ho='L'
    return ho
def get_aw(df):
    if df['FullTimeResult']=='D':
        aw='D'
    elif df['FullTimeResult']=='H':
        aw='L'
    else:
        aw='W'
    return aw
df2['HO']=df2.apply(get_ho,axis=1)
df2['AW']=df2.apply(get_aw,axis=1)
df2.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeGoalsMeanL5,AwayGoalsMeanL5,HomeGoalsConcededL5,AwayGoalsConcededL5,HomeGoalDFMeanL5,AwayGoalDFMeanL5,HomePointsL5,AwayPointsL5,HO,AW
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W,L
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W,L
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L,W
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,D
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,W,L

In [50]:
def calc_win_streak(results):
    streak=0
    out=[]
    for result in results:
        out.append(streak)
        if result=='W':
            streak+=1
        elif result=='L' or result=='D':
            streak=0
    return out
df2['WinStreakL5Home']=df2.groupby('HomeTeam')['HO'].transform(calc_win_streak)
df2['WinStreakL5Away']=df2.groupby('AwayTeam')['AW'].transform(calc_win_streak)
df2.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeGoalsConcededL5,AwayGoalsConcededL5,HomeGoalDFMeanL5,AwayGoalDFMeanL5,HomePointsL5,AwayPointsL5,HO,AW,WinStreakL5Home,WinStreakL5Away
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,W,L,0,0
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,W,L,0,0
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,L,W,0,0
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,D,D,0,0
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,W,L,0,0

In [51]:
df2.sample(10)

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeGoalsConcededL5,AwayGoalsConcededL5,HomeGoalDFMeanL5,AwayGoalDFMeanL5,HomePointsL5,AwayPointsL5,HO,AW,WinStreakL5Home,WinStreakL5Away
6217,2016/17,2017-02-01,Man United,Hull,0,0,D,0,0,D,...,0.8,2.0,0.8,-1.8,2.2,0.0,D,D,0,0
3744,2010/11,2010-09-11,Newcastle,Blackpool,0,2,A,0,1,A,...,0.8,3.0,1.0,-1.0,1.4,1.5,L,W,1,0
179,2000/01,2000-12-22,Coventry,Southampton,1,1,D,1,0,H,...,1.0,2.4,0.0,-1.6,1.4,0.4,D,D,1,0
8300,2022/23,2022-08-27,Southampton,Man United,0,1,A,0,0,D,...,2.4,3.2,-1.4,-3.0,0.8,0.0,L,W,0,0
4429,2011/12,2012-04-21,Fulham,Wigan,2,1,H,0,0,D,...,1.2,1.2,0.8,0.4,2.0,2.0,W,L,0,1
3258,2008/09,2009-04-05,Man United,Aston Villa,3,2,H,1,1,D,...,1.0,1.6,0.6,-0.6,2.4,1.8,W,L,0,0
6636,2017/18,2018-02-11,Huddersfield,Bournemouth,4,1,H,2,1,H,...,2.2,1.6,-1.6,-0.4,0.4,1.0,W,L,0,1
358,2000/01,2001-05-05,Bradford,Middlesbrough,1,1,D,1,0,H,...,1.2,0.8,0.4,1.2,1.6,2.0,D,D,0,2
6434,2017/18,2017-09-30,Stoke,Southampton,2,1,H,1,0,H,...,2.0,1.0,-1.2,0.0,1.0,1.6,W,L,0,1
3780,2010/11,2010-10-16,Arsenal,Birmingham,2,1,H,1,1,D,...,0.8,2.0,2.4,-0.8,2.0,0.4,W,L,0,0

In [52]:
team_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18760 entries, 0 to 18759
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MatchDate         18760 non-null  datetime64[ns]
 1   Season            18760 non-null  object
 2   Team              18760 non-null  object
 3   Opponent          18760 non-null  object
 4   Venue             18760 non-null  object
 5   Shots             18760 non-null  int64
 6   GoalsFor          18760 non-null  int64
 7   GoalsAgainst      18760 non-null  int64
 8   Result            18760 non-null  object
 9   RedCard           18760 non-null  int64
 10  GoalsConcededL5   18714 non-null  float64
 11  GoalsMeanL5       18714 non-null  float64
 12  ShotsOTMeanL5     18714 non-null  float64
 13  points            18760 non-null  int64
 14  PointsMeanL5      18714 non-null  float64
 15  goal_df           18760 non-null  int64
 16  GoalDFMeanL5      18714 non-null  float64
 17  RedCardL2         18714 non-null  float64
 18  GoalDFMeanL10     18714 non-null  float64
 19  ShotsOTMeanL10    18714 non-null  float64
 20  PointsMeanL10     18714 non-null  float64
 21  GoalsMeanL10      18714 non-null  float64
 22  GoalsConcededL10  18714 non-null  float64
 23  outcome           18760 non-null  object
 24  win_streak        18760 non-null  int64
 25  RestDays          18714 non-null  float64
 26  H2HL5             17172 non-null  float64
dtypes: datetime64[ns](1), float64(13), int64(7), object(6)
memory usage: 3.9+ MB

In [53]:
team_df.head()

,MatchDate,Season,Team,Opponent,Venue,Shots,GoalsFor,GoalsAgainst,Result,RedCard,...,RedCardL2,GoalDFMeanL10,ShotsOTMeanL10,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,outcome,win_streak,RestDays,H2HL5
0,2000-08-19,2000/01,Arsenal,Sunderland,Away,7,0,1,H,1,...,NaN,NaN,NaN,NaN,NaN,NaN,L,0,NaN,NaN
1,2000-08-21,2000/01,Arsenal,Liverpool,Home,12,2,0,H,1,...,1.0,-1.00,7.000000,0.00,0.000000,1.000000,W,0,2.0,NaN
2,2000-08-26,2000/01,Arsenal,Charlton,Home,9,5,3,H,0,...,1.0,0.50,9.500000,1.50,1.000000,0.500000,W,1,5.0,NaN
3,2000-09-06,2000/01,Arsenal,Chelsea,Away,5,2,2,D,0,...,0.5,1.00,9.333333,2.00,2.333333,1.333333,D,2,11.0,NaN
4,2000-09-09,2000/01,Arsenal,Bradford,Away,11,1,1,D,0,...,0.0,0.75,8.250000,1.75,2.250000,1.500000,D,0,3.0,NaN

In [54]:
overall_feat=team_df[
    ['MatchDate','Team','GoalsConcededL5','GoalsMeanL5','ShotsOTMeanL10','GoalDFMeanL10','GoalDFMeanL5','PointsMeanL5','PointsMeanL10','GoalsMeanL10','GoalsConcededL10',
    'win_streak','RestDays','H2HL5','RedCardL2']
]

In [55]:
overall_feat.head()

,MatchDate,Team,GoalsConcededL5,GoalsMeanL5,ShotsOTMeanL10,GoalDFMeanL10,GoalDFMeanL5,PointsMeanL5,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,win_streak,RestDays,H2HL5,RedCardL2
0,2000-08-19,Arsenal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1,2000-08-21,Arsenal,1.000000,0.000000,7.000000,-1.00,-1.00,0.00,0.00,0.000000,1.000000,0,2.0,NaN,1.0
2,2000-08-26,Arsenal,0.500000,1.000000,9.500000,0.50,0.50,1.50,1.50,1.000000,0.500000,1,5.0,NaN,1.0
3,2000-09-06,Arsenal,1.333333,2.333333,9.333333,1.00,1.00,2.00,2.00,2.333333,1.333333,2,11.0,NaN,0.5
4,2000-09-09,Arsenal,1.500000,2.250000,8.250000,0.75,0.75,1.75,1.75,2.250000,1.500000,0,3.0,NaN,0.0

In [56]:
df2['MatchDate'] = pd.to_datetime(df2['MatchDate'])

In [57]:
#merge
df3 = df2.merge(
    overall_feat,
    left_on=['MatchDate', 'HomeTeam'],
    right_on=['MatchDate', 'Team'],
    how='left'
)
df3.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,GoalDFMeanL10,GoalDFMeanL5,PointsMeanL5,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,win_streak,RestDays,H2HL5,RedCardL2
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN

In [58]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 49 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Season               9380 non-null   object
 1   MatchDate            9380 non-null   datetime64[ns]
 2   HomeTeam             9380 non-null   object
 3   AwayTeam             9380 non-null   object
 4   FullTimeHomeGoals    9380 non-null   int64
 5   FullTimeAwayGoals    9380 non-null   int64
 6   FullTimeResult       9380 non-null   object
 7   HalfTimeHomeGoals    9380 non-null   int64
 8   HalfTimeAwayGoals    9380 non-null   int64
 9   HalfTimeResult       9380 non-null   object
 10  HomeShots            9380 non-null   int64
 11  AwayShots            9380 non-null   int64
 12  HomeShotsOnTarget    9380 non-null   int64
 13  AwayShotsOnTarget    9380 non-null   int64
 14  HomeCorners          9380 non-null   int64
 15  AwayCorners          9380 non-null   int64
 16  HomeFouls            9380 non-null   int64
 17  AwayFouls            9380 non-null   int64
 18  HomeYellowCards      9380 non-null   int64
 19  AwayYellowCards      9380 non-null   int64
 20  HomeRedCards         9380 non-null   int64
 21  AwayRedCards         9380 non-null   int64
 22  era                  9380 non-null   int64
 23  HomeGoalsMeanL5      9334 non-null   float64
 24  AwayGoalsMeanL5      9334 non-null   float64
 25  HomeGoalsConcededL5  9334 non-null   float64
 26  AwayGoalsConcededL5  9334 non-null   float64
 27  HomeGoalDFMeanL5     9334 non-null   float64
 28  AwayGoalDFMeanL5     9334 non-null   float64
 29  HomePointsL5         9334 non-null   float64
 30  AwayPointsL5         9334 non-null   float64
 31  HO                   9380 non-null   object
 32  AW                   9380 non-null   object
 33  WinStreakL5Home      9380 non-null   int64
 34  WinStreakL5Away      9380 non-null   int64
 35  Team                 9380 non-null   object
 36  GoalsConcededL5      9360 non-null   float64
 37  GoalsMeanL5          9360 non-null   float64
 38  ShotsOTMeanL10       9360 non-null   float64
 39  GoalDFMeanL10        9360 non-null   float64
 40  GoalDFMeanL5         9360 non-null   float64
 41  PointsMeanL5         9360 non-null   float64
 42  PointsMeanL10        9360 non-null   float64
 43  GoalsMeanL10         9360 non-null   float64
 44  GoalsConcededL10     9360 non-null   float64
 45  win_streak           9380 non-null   int64
 46  RestDays             9360 non-null   float64
 47  H2HL5                8586 non-null   float64
 48  RedCardL2            9360 non-null   float64
dtypes: datetime64[ns](1), float64(20), int64(20), object(8)
memory usage: 3.5+ MB

In [59]:
def rename(df, columns):
    rename_dict = {
        col: f'{col}Venuedpd'
        for col in columns
    }

    return df.rename(columns=rename_dict)
feat_col=['HomeGoalsMeanL5','AwayGoalsMeanL5','HomeGoalsConcededL5','AwayGoalsConcededL5','HomeGoalDFMeanL5','AwayGoalDFMeanL5','HomePointsL5','AwayPointsL5']
df3 = rename(df3, feat_col)
df3.drop(columns=['Team'],inplace=True)
df3.sample(10)

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,GoalDFMeanL10,GoalDFMeanL5,PointsMeanL5,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,win_streak,RestDays,H2HL5,RedCardL2
6938,2018/19,2018-12-26,Watford,Chelsea,1,2,A,1,1,D,...,0.1,0.0,1.4,1.4,1.4,1.3,2,4.0,0.800000,0.0
8961,2023/24,2024-04-07,Sheffield United,Chelsea,2,2,D,1,1,D,...,-1.8,-1.8,0.4,0.6,1.3,3.1,0,3.0,0.800000,0.0
1173,2003/04,2003-08-30,Newcastle,Birmingham,0,1,A,0,0,D,...,-0.1,0.2,1.6,1.2,1.7,1.8,0,7.0,3.000000,0.0
3670,2009/10,2010-04-17,Man City,Man United,0,1,A,0,0,D,...,1.5,2.2,2.4,2.1,2.4,0.9,3,6.0,1.200000,0.0
2800,2007/08,2008-01-29,Arsenal,Newcastle,3,0,H,1,0,H,...,1.0,1.6,2.2,2.1,1.7,0.7,1,10.0,1.200000,0.0
6011,2016/17,2016-08-27,Everton,Stoke,1,0,H,0,0,D,...,-0.4,-0.2,1.4,1.3,1.1,1.5,1,7.0,0.800000,0.0
8094,2021/22,2022-01-21,Watford,Norwich,0,3,A,0,0,D,...,-0.9,-1.4,0.2,0.4,1.1,2.0,0,6.0,2.400000,0.0
533,2001/02,2001-12-09,Ipswich,Newcastle,0,1,A,0,1,A,...,-1.0,-1.0,0.2,0.4,0.9,1.9,0,8.0,1.500000,0.0
8901,2023/24,2024-02-24,Aston Villa,Nott'm Forest,4,2,H,3,1,H,...,0.5,0.6,1.4,1.7,1.8,1.3,1,7.0,1.333333,0.0
8065,2021/22,2021-12-27,Newcastle,Man United,1,1,D,1,0,H,...,-1.4,-1.8,0.8,0.7,0.8,2.2,0,8.0,0.600000,0.0

In [60]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Season                       9380 non-null   object
 1   MatchDate                    9380 non-null   datetime64[ns]
 2   HomeTeam                     9380 non-null   object
 3   AwayTeam                     9380 non-null   object
 4   FullTimeHomeGoals            9380 non-null   int64
 5   FullTimeAwayGoals            9380 non-null   int64
 6   FullTimeResult               9380 non-null   object
 7   HalfTimeHomeGoals            9380 non-null   int64
 8   HalfTimeAwayGoals            9380 non-null   int64
 9   HalfTimeResult               9380 non-null   object
 10  HomeShots                    9380 non-null   int64
 11  AwayShots                    9380 non-null   int64
 12  HomeShotsOnTarget            9380 non-null   int64
 13  AwayShotsOnTarget            9380 non-null   int64
 14  HomeCorners                  9380 non-null   int64
 15  AwayCorners                  9380 non-null   int64
 16  HomeFouls                    9380 non-null   int64
 17  AwayFouls                    9380 non-null   int64
 18  HomeYellowCards              9380 non-null   int64
 19  AwayYellowCards              9380 non-null   int64
 20  HomeRedCards                 9380 non-null   int64
 21  AwayRedCards                 9380 non-null   int64
 22  era                          9380 non-null   int64
 23  HomeGoalsMeanL5Venuedpd      9334 non-null   float64
 24  AwayGoalsMeanL5Venuedpd      9334 non-null   float64
 25  HomeGoalsConcededL5Venuedpd  9334 non-null   float64
 26  AwayGoalsConcededL5Venuedpd  9334 non-null   float64
 27  HomeGoalDFMeanL5Venuedpd     9334 non-null   float64
 28  AwayGoalDFMeanL5Venuedpd     9334 non-null   float64
 29  HomePointsL5Venuedpd         9334 non-null   float64
 30  AwayPointsL5Venuedpd         9334 non-null   float64
 31  HO                           9380 non-null   object
 32  AW                           9380 non-null   object
 33  WinStreakL5Home              9380 non-null   int64
 34  WinStreakL5Away              9380 non-null   int64
 35  GoalsConcededL5              9360 non-null   float64
 36  GoalsMeanL5                  9360 non-null   float64
 37  ShotsOTMeanL10               9360 non-null   float64
 38  GoalDFMeanL10                9360 non-null   float64
 39  GoalDFMeanL5                 9360 non-null   float64
 40  PointsMeanL5                 9360 non-null   float64
 41  PointsMeanL10                9360 non-null   float64
 42  GoalsMeanL10                 9360 non-null   float64
 43  GoalsConcededL10             9360 non-null   float64
 44  win_streak                   9380 non-null   int64
 45  RestDays                     9360 non-null   float64
 46  H2HL5                        8586 non-null   float64
 47  RedCardL2                    9360 non-null   float64
dtypes: datetime64[ns](1), float64(20), int64(20), object(7)
memory usage: 3.4+ MB

In [61]:
def rename_feat(df, columns,suffix):
    rename_dict = {
        col: f'{suffix}{col}'
        for col in columns
    }

    return df.rename(columns=rename_dict)
feat_col=['GoalsConcededL5','GoalsMeanL5','ShotsOTMeanL10','GoalDFMeanL10','GoalDFMeanL5','PointsMeanL5','PointsMeanL10','GoalsMeanL10','GoalsConcededL10',
    'win_streak','RestDays','H2HL5']
df3 = rename_feat(df3, feat_col,'Home')
df3.sample(10)

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,HomeGoalDFMeanL10,HomeGoalDFMeanL5,HomePointsMeanL5,HomePointsMeanL10,HomeGoalsMeanL10,HomeGoalsConcededL10,Homewin_streak,HomeRestDays,HomeH2HL5,RedCardL2
3848,2010/11,2010-11-21,Fulham,Man City,1,4,A,0,3,A,...,0.0,0.0,1.0,1.1,0.9,0.9,0,8.0,1.6,0.0
2854,2007/08,2008-03-09,Wigan,Arsenal,0,0,D,0,0,D,...,0.0,0.0,1.4,1.4,0.8,0.8,0,8.0,0.0,0.0
7197,2019/20,2019-09-28,Everton,Man City,1,3,A,1,1,D,...,0.2,-0.8,1.2,1.5,1.3,1.1,0,7.0,0.8,0.0
7352,2019/20,2020-01-18,Arsenal,Sheffield United,1,1,D,1,0,H,...,-0.1,0.2,1.2,1.1,1.3,1.4,0,7.0,1.0,0.5
6086,2016/17,2016-10-29,Sunderland,Arsenal,1,4,A,0,1,A,...,-1.0,-1.0,0.2,0.3,0.8,1.8,0,7.0,0.4,0.0
4575,2012/13,2012-11-10,Southampton,Swansea,1,1,D,0,0,D,...,-1.4,-1.6,0.2,0.4,1.4,2.8,0,5.0,NaN,0.0
8022,2021/22,2021-12-01,Watford,Chelsea,1,2,A,1,1,D,...,-0.4,0.4,1.2,1.0,1.5,1.9,0,3.0,0.6,0.0
574,2001/02,2001-12-29,Everton,Charlton,0,3,A,0,1,A,...,-0.5,-1.0,0.6,0.9,0.8,1.3,0,3.0,2.0,0.0
8379,2022/23,2022-10-22,Chelsea,Man United,1,1,D,0,0,D,...,0.5,1.4,2.6,2.0,1.5,1.0,0,3.0,0.8,0.0
457,2001/02,2001-10-14,Aston Villa,Fulham,2,0,H,0,0,D,...,0.4,1.2,2.2,1.7,1.2,0.8,2,14.0,NaN,0.5

In [62]:
df3=rename_feat(df3,['RedCardL2'],'Home')

In [63]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Season                       9380 non-null   object
 1   MatchDate                    9380 non-null   datetime64[ns]
 2   HomeTeam                     9380 non-null   object
 3   AwayTeam                     9380 non-null   object
 4   FullTimeHomeGoals            9380 non-null   int64
 5   FullTimeAwayGoals            9380 non-null   int64
 6   FullTimeResult               9380 non-null   object
 7   HalfTimeHomeGoals            9380 non-null   int64
 8   HalfTimeAwayGoals            9380 non-null   int64
 9   HalfTimeResult               9380 non-null   object
 10  HomeShots                    9380 non-null   int64
 11  AwayShots                    9380 non-null   int64
 12  HomeShotsOnTarget            9380 non-null   int64
 13  AwayShotsOnTarget            9380 non-null   int64
 14  HomeCorners                  9380 non-null   int64
 15  AwayCorners                  9380 non-null   int64
 16  HomeFouls                    9380 non-null   int64
 17  AwayFouls                    9380 non-null   int64
 18  HomeYellowCards              9380 non-null   int64
 19  AwayYellowCards              9380 non-null   int64
 20  HomeRedCards                 9380 non-null   int64
 21  AwayRedCards                 9380 non-null   int64
 22  era                          9380 non-null   int64
 23  HomeGoalsMeanL5Venuedpd      9334 non-null   float64
 24  AwayGoalsMeanL5Venuedpd      9334 non-null   float64
 25  HomeGoalsConcededL5Venuedpd  9334 non-null   float64
 26  AwayGoalsConcededL5Venuedpd  9334 non-null   float64
 27  HomeGoalDFMeanL5Venuedpd     9334 non-null   float64
 28  AwayGoalDFMeanL5Venuedpd     9334 non-null   float64
 29  HomePointsL5Venuedpd         9334 non-null   float64
 30  AwayPointsL5Venuedpd         9334 non-null   float64
 31  HO                           9380 non-null   object
 32  AW                           9380 non-null   object
 33  WinStreakL5Home              9380 non-null   int64
 34  WinStreakL5Away              9380 non-null   int64
 35  HomeGoalsConcededL5          9360 non-null   float64
 36  HomeGoalsMeanL5              9360 non-null   float64
 37  HomeShotsOTMeanL10           9360 non-null   float64
 38  HomeGoalDFMeanL10            9360 non-null   float64
 39  HomeGoalDFMeanL5             9360 non-null   float64
 40  HomePointsMeanL5             9360 non-null   float64
 41  HomePointsMeanL10            9360 non-null   float64
 42  HomeGoalsMeanL10             9360 non-null   float64
 43  HomeGoalsConcededL10         9360 non-null   float64
 44  Homewin_streak               9380 non-null   int64
 45  HomeRestDays                 9360 non-null   float64
 46  HomeH2HL5                    8586 non-null   float64
 47  HomeRedCardL2                9360 non-null   float64
dtypes: datetime64[ns](1), float64(20), int64(20), object(7)
memory usage: 3.4+ MB

In [64]:
df4 = df3.merge(
    overall_feat,
    left_on=['MatchDate', 'AwayTeam'],
    right_on=['MatchDate', 'Team'],
    how='left'
)
df4.head()

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,GoalDFMeanL10,GoalDFMeanL5,PointsMeanL5,PointsMeanL10,GoalsMeanL10,GoalsConcededL10,win_streak,RestDays,H2HL5,RedCardL2
0,2000/01,2000-08-19,Charlton,Man City,4,0,H,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1,2000/01,2000-08-19,Chelsea,West Ham,4,2,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
2,2000/01,2000-08-19,Coventry,Middlesbrough,1,3,A,1,1,D,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
3,2000/01,2000-08-19,Derby,Southampton,2,2,D,1,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
4,2000/01,2000-08-19,Leeds,Everton,2,0,H,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN

In [65]:
feat_col2=feat_col+['RedCardL2']

In [66]:
df4 = rename_feat(df4, feat_col2,'Away')
df4.drop(columns=['Team'],inplace=True)
df4.sample(10)

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,HalfTimeHomeGoals,HalfTimeAwayGoals,HalfTimeResult,...,AwayGoalDFMeanL10,AwayGoalDFMeanL5,AwayPointsMeanL5,AwayPointsMeanL10,AwayGoalsMeanL10,AwayGoalsConcededL10,Awaywin_streak,AwayRestDays,AwayH2HL5,AwayRedCardL2
3617,2009/10,2010-03-13,Tottenham,Blackburn,3,1,H,1,0,H,...,0.0,0.0,1.4,1.5,1.3,1.3,0,13.0,1.400000,0.0
6599,2017/18,2018-01-15,Man United,Stoke,3,0,H,2,0,H,...,-1.5,-1.4,0.8,0.7,0.8,2.3,0,14.0,1.200000,0.0
5087,2013/14,2014-02-02,Arsenal,Crystal Palace,2,0,H,0,0,D,...,-0.1,-0.2,1.4,1.6,0.8,0.9,2,5.0,0.333333,0.0
2756,2007/08,2007-12-26,Wigan,Newcastle,1,0,H,0,0,D,...,-0.5,0.0,1.6,1.2,1.3,1.8,0,3.0,1.800000,0.0
4600,2012/13,2012-11-27,Sunderland,QPR,0,0,D,0,0,D,...,-0.9,-1.2,0.2,0.3,0.8,1.7,0,3.0,0.000000,0.0
1273,2003/04,2003-11-29,Charlton,Leeds,0,1,A,0,1,A,...,-2.1,-2.6,0.0,0.6,0.8,2.9,0,7.0,2.000000,0.0
7942,2021/22,2021-09-25,Everton,Norwich,2,0,H,1,0,H,...,-2.5,-2.4,0.0,0.0,0.3,2.8,0,7.0,0.800000,0.0
2765,2007/08,2007-12-29,Wigan,Aston Villa,1,2,A,1,0,H,...,0.7,-0.6,0.6,1.6,2.0,1.3,0,3.0,0.500000,0.5
907,2002/03,2002-11-24,Charlton,Blackburn,3,1,H,0,0,D,...,0.4,0.6,1.6,1.5,1.6,1.2,0,7.0,3.000000,0.5
8885,2023/24,2024-02-11,West Ham,Arsenal,0,6,A,0,4,A,...,0.8,1.0,1.8,1.9,2.0,1.2,3,7.0,2.000000,0.0

In [67]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 61 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Season                       9380 non-null   object
 1   MatchDate                    9380 non-null   datetime64[ns]
 2   HomeTeam                     9380 non-null   object
 3   AwayTeam                     9380 non-null   object
 4   FullTimeHomeGoals            9380 non-null   int64
 5   FullTimeAwayGoals            9380 non-null   int64
 6   FullTimeResult               9380 non-null   object
 7   HalfTimeHomeGoals            9380 non-null   int64
 8   HalfTimeAwayGoals            9380 non-null   int64
 9   HalfTimeResult               9380 non-null   object
 10  HomeShots                    9380 non-null   int64
 11  AwayShots                    9380 non-null   int64
 12  HomeShotsOnTarget            9380 non-null   int64
 13  AwayShotsOnTarget            9380 non-null   int64
 14  HomeCorners                  9380 non-null   int64
 15  AwayCorners                  9380 non-null   int64
 16  HomeFouls                    9380 non-null   int64
 17  AwayFouls                    9380 non-null   int64
 18  HomeYellowCards              9380 non-null   int64
 19  AwayYellowCards              9380 non-null   int64
 20  HomeRedCards                 9380 non-null   int64
 21  AwayRedCards                 9380 non-null   int64
 22  era                          9380 non-null   int64
 23  HomeGoalsMeanL5Venuedpd      9334 non-null   float64
 24  AwayGoalsMeanL5Venuedpd      9334 non-null   float64
 25  HomeGoalsConcededL5Venuedpd  9334 non-null   float64
 26  AwayGoalsConcededL5Venuedpd  9334 non-null   float64
 27  HomeGoalDFMeanL5Venuedpd     9334 non-null   float64
 28  AwayGoalDFMeanL5Venuedpd     9334 non-null   float64
 29  HomePointsL5Venuedpd         9334 non-null   float64
 30  AwayPointsL5Venuedpd         9334 non-null   float64
 31  HO                           9380 non-null   object
 32  AW                           9380 non-null   object
 33  WinStreakL5Home              9380 non-null   int64
 34  WinStreakL5Away              9380 non-null   int64
 35  HomeGoalsConcededL5          9360 non-null   float64
 36  HomeGoalsMeanL5              9360 non-null   float64
 37  HomeShotsOTMeanL10           9360 non-null   float64
 38  HomeGoalDFMeanL10            9360 non-null   float64
 39  HomeGoalDFMeanL5             9360 non-null   float64
 40  HomePointsMeanL5             9360 non-null   float64
 41  HomePointsMeanL10            9360 non-null   float64
 42  HomeGoalsMeanL10             9360 non-null   float64
 43  HomeGoalsConcededL10         9360 non-null   float64
 44  Homewin_streak               9380 non-null   int64
 45  HomeRestDays                 9360 non-null   float64
 46  HomeH2HL5                    8586 non-null   float64
 47  HomeRedCardL2                9360 non-null   float64
 48  AwayGoalsConcededL5          9354 non-null   float64
 49  AwayGoalsMeanL5              9354 non-null   float64
 50  AwayShotsOTMeanL10           9354 non-null   float64
 51  AwayGoalDFMeanL10            9354 non-null   float64
 52  AwayGoalDFMeanL5             9354 non-null   float64
 53  AwayPointsMeanL5             9354 non-null   float64
 54  AwayPointsMeanL10            9354 non-null   float64
 55  AwayGoalsMeanL10             9354 non-null   float64
 56  AwayGoalsConcededL10         9354 non-null   float64
 57  Awaywin_streak               9380 non-null   int64
 58  AwayRestDays                 9354 non-null   float64
 59  AwayH2HL5                    8586 non-null   float64
 60  AwayRedCardL2                9354 non-null   float64
dtypes: datetime64[ns](1), float64(32), int64(21), object(7)
memory usage: 4.4+ MB

In [68]:
df4[['HomeGoalsMeanL5Venuedpd','AwayGoalsMeanL5Venuedpd','HomeH2HL5','AwayH2HL5','FullTimeResult']].sample(10)

,HomeGoalsMeanL5Venuedpd,AwayGoalsMeanL5Venuedpd,HomeH2HL5,AwayH2HL5,FullTimeResult
6290,2.6,2.0,1.0,1.60,H
6895,2.0,1.0,3.0,0.00,D
7713,1.4,2.2,0.2,2.60,A
1799,1.6,1.2,0.6,1.80,D
6064,3.0,1.2,2.2,0.40,D
6547,1.2,2.8,1.0,1.75,A
133,0.8,2.0,NaN,NaN,A
2860,0.4,2.4,0.8,2.00,A
972,1.0,1.8,1.0,2.00,D
3355,3.6,1.0,1.8,0.60,A

In [69]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9380 entries, 0 to 9379
Data columns (total 61 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Season                       9380 non-null   object
 1   MatchDate                    9380 non-null   datetime64[ns]
 2   HomeTeam                     9380 non-null   object
 3   AwayTeam                     9380 non-null   object
 4   FullTimeHomeGoals            9380 non-null   int64
 5   FullTimeAwayGoals            9380 non-null   int64
 6   FullTimeResult               9380 non-null   object
 7   HalfTimeHomeGoals            9380 non-null   int64
 8   HalfTimeAwayGoals            9380 non-null   int64
 9   HalfTimeResult               9380 non-null   object
 10  HomeShots                    9380 non-null   int64
 11  AwayShots                    9380 non-null   int64
 12  HomeShotsOnTarget            9380 non-null   int64
 13  AwayShotsOnTarget            9380 non-null   int64
 14  HomeCorners                  9380 non-null   int64
 15  AwayCorners                  9380 non-null   int64
 16  HomeFouls                    9380 non-null   int64
 17  AwayFouls                    9380 non-null   int64
 18  HomeYellowCards              9380 non-null   int64
 19  AwayYellowCards              9380 non-null   int64
 20  HomeRedCards                 9380 non-null   int64
 21  AwayRedCards                 9380 non-null   int64
 22  era                          9380 non-null   int64
 23  HomeGoalsMeanL5Venuedpd      9334 non-null   float64
 24  AwayGoalsMeanL5Venuedpd      9334 non-null   float64
 25  HomeGoalsConcededL5Venuedpd  9334 non-null   float64
 26  AwayGoalsConcededL5Venuedpd  9334 non-null   float64
 27  HomeGoalDFMeanL5Venuedpd     9334 non-null   float64
 28  AwayGoalDFMeanL5Venuedpd     9334 non-null   float64
 29  HomePointsL5Venuedpd         9334 non-null   float64
 30  AwayPointsL5Venuedpd         9334 non-null   float64
 31  HO                           9380 non-null   object
 32  AW                           9380 non-null   object
 33  WinStreakL5Home              9380 non-null   int64
 34  WinStreakL5Away              9380 non-null   int64
 35  HomeGoalsConcededL5          9360 non-null   float64
 36  HomeGoalsMeanL5              9360 non-null   float64
 37  HomeShotsOTMeanL10           9360 non-null   float64
 38  HomeGoalDFMeanL10            9360 non-null   float64
 39  HomeGoalDFMeanL5             9360 non-null   float64
 40  HomePointsMeanL5             9360 non-null   float64
 41  HomePointsMeanL10            9360 non-null   float64
 42  HomeGoalsMeanL10             9360 non-null   float64
 43  HomeGoalsConcededL10         9360 non-null   float64
 44  Homewin_streak               9380 non-null   int64
 45  HomeRestDays                 9360 non-null   float64
 46  HomeH2HL5                    8586 non-null   float64
 47  HomeRedCardL2                9360 non-null   float64
 48  AwayGoalsConcededL5          9354 non-null   float64
 49  AwayGoalsMeanL5              9354 non-null   float64
 50  AwayShotsOTMeanL10           9354 non-null   float64
 51  AwayGoalDFMeanL10            9354 non-null   float64
 52  AwayGoalDFMeanL5             9354 non-null   float64
 53  AwayPointsMeanL5             9354 non-null   float64
 54  AwayPointsMeanL10            9354 non-null   float64
 55  AwayGoalsMeanL10             9354 non-null   float64
 56  AwayGoalsConcededL10         9354 non-null   float64
 57  Awaywin_streak               9380 non-null   int64
 58  AwayRestDays                 9354 non-null   float64
 59  AwayH2HL5                    8586 non-null   float64
 60  AwayRedCardL2                9354 non-null   float64
dtypes: datetime64[ns](1), float64(32), int64(21), object(7)
memory usage: 4.4+ MB

In [70]:
df5=df4.drop(columns=['HalfTimeHomeGoals','HalfTimeAwayGoals','HalfTimeResult','HomeShots','AwayShots','HomeShotsOnTarget','AwayShotsOnTarget','HomeRedCards','AwayRedCards','HomeYellowCards','AwayYellowCards',
                     'HomeFouls','AwayFouls','HomeCorners','AwayCorners','HO','AW'
                     ])
df5.sample(10)

,Season,MatchDate,HomeTeam,AwayTeam,FullTimeHomeGoals,FullTimeAwayGoals,FullTimeResult,era,HomeGoalsMeanL5Venuedpd,AwayGoalsMeanL5Venuedpd,...,AwayGoalDFMeanL10,AwayGoalDFMeanL5,AwayPointsMeanL5,AwayPointsMeanL10,AwayGoalsMeanL10,AwayGoalsConcededL10,Awaywin_streak,AwayRestDays,AwayH2HL5,AwayRedCardL2
8442,2022/23,2023-01-04,Leeds,West Ham,2,2,D,4,1.4,0.4,...,-0.3,-1.6,0.0,1.0,1.0,1.3,0,5.0,1.8,0.0
6630,2017/18,2018-02-10,Stoke,Brighton,1,1,D,9,1.0,0.2,...,-0.7,-0.8,1.0,1.0,0.7,1.4,1,7.0,1.0,0.0
3146,2008/09,2008-12-29,Man United,Middlesbrough,1,0,H,18,3.2,1.0,...,-0.4,-1.0,0.4,1.0,0.9,1.3,0,3.0,0.6,0.0
6307,2016/17,2017-04-15,Sunderland,West Ham,2,2,D,10,0.0,1.4,...,-0.8,-1.0,0.6,0.8,1.3,2.1,1,7.0,2.2,0.0
8412,2022/23,2022-11-12,Newcastle,Chelsea,1,0,H,4,2.2,1.2,...,0.3,-0.4,1.0,1.7,1.4,1.1,0,6.0,2.4,0.0
6589,2017/18,2018-01-04,Tottenham,West Ham,1,1,D,9,2.8,1.4,...,-0.3,0.6,1.6,1.2,1.3,1.6,1,2.0,1.2,0.0
547,2001/02,2001-12-18,Arsenal,Newcastle,1,3,A,25,2.4,2.0,...,0.6,0.2,2.0,1.9,1.6,1.0,2,3.0,0.5,0.0
1863,2005/06,2005-09-18,Man City,Bolton,0,1,A,21,1.2,1.4,...,0.5,0.4,1.6,1.8,1.3,0.8,0,7.0,1.2,0.0
3164,2008/09,2009-01-18,Tottenham,Portsmouth,1,1,D,18,0.6,0.8,...,-0.7,-1.6,0.2,0.9,1.1,1.8,0,21.0,0.8,0.0
5137,2013/14,2014-03-15,Stoke,West Ham,3,1,H,13,1.6,1.0,...,0.6,1.4,2.4,1.7,1.6,1.0,0,14.0,1.6,0.0

In [71]:
df5.isnull().sum()

Season                           0
MatchDate                        0
HomeTeam                         0
AwayTeam                         0
FullTimeHomeGoals                0
FullTimeAwayGoals                0
FullTimeResult                   0
era                              0
HomeGoalsMeanL5Venuedpd         46
AwayGoalsMeanL5Venuedpd         46
HomeGoalsConcededL5Venuedpd     46
AwayGoalsConcededL5Venuedpd     46
HomeGoalDFMeanL5Venuedpd        46
AwayGoalDFMeanL5Venuedpd        46
HomePointsL5Venuedpd            46
AwayPointsL5Venuedpd            46
WinStreakL5Home                  0
WinStreakL5Away                  0
HomeGoalsConcededL5             20
HomeGoalsMeanL5                 20
HomeShotsOTMeanL10              20
HomeGoalDFMeanL10               20
HomeGoalDFMeanL5                20
HomePointsMeanL5                20
HomePointsMeanL10               20
HomeGoalsMeanL10                20
HomeGoalsConcededL10            20
Homewin_streak                   0
HomeRestDays                    20
HomeH2HL5                      794
HomeRedCardL2                   20
AwayGoalsConcededL5             26
AwayGoalsMeanL5                 26
AwayShotsOTMeanL10              26
AwayGoalDFMeanL10               26
AwayGoalDFMeanL5                26
AwayPointsMeanL5                26
AwayPointsMeanL10               26
AwayGoalsMeanL10                26
AwayGoalsConcededL10            26
Awaywin_streak                   0
AwayRestDays                    26
AwayH2HL5                      794
AwayRedCardL2                   26
dtype: int64

In [ ]:
df5['HomeGoalsConcededL5']=df5['HomeGoalsConcededL5'].fillna(df5.groupby('HomeTeam')['HomeGoalsConcededL5'].transform)

In [72]:
class PreProcessor:
    def __init__(self):

_IncompleteInputError: incomplete input (3141654834.py, line 2)